name: 'yReBZynHUPCTYcv6GK32p'

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout from repo
      uses: actions/checkout@main
      with:
        ref: main

    - name: Install Python latest
      uses: actions/setup-python@main
      with:
        python-version: '3.x'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Doing fetch and convert
      run: python yReBZynHUPCTYcv6GK2p.py  -l http://www.ximalaya.com/album/49547055.xml
